
---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Coding with the Machines

This repository contains replication materials for a paper examining the relative performance of supervised and semi-supervised algorithms in coding political data.

## Main Code File

The main code file for this project is `main_04_08_2024.R`, located in the `code` folder of this GitHub repository.

## Overview

The aim of this project is to provide researchers with the necessary materials to replicate the analysis conducted in the associated paper. 

## Files

In addition to the main code file, other necessary files can be found in the `code` folder within this GitHub repository. 

## Usage

To replicate the analysis conducted in the associated paper, follow these steps:

1. Clone or download this GitHub repository to your local machine.
2. Open the `main_04_08_2024.R` file in your preferred R environment.
3. Review the code and associated documentation to understand the analysis workflow.
4. Execute the code in your R environment to replicate the results of the paper.
